### ISSUE TITLE
"Segmentation fault" error

### ISSUE THREAD

**Issue by attitudezoe** [alphacep/kaldi-websocket-python#10]
Hi,

I tried to add big lm re-scoring in kaldi_recognizer.cc, 
There was no problem in create _kaldi_recognizer.so and run asr_server.py,
but when run test.py , I got the following error:
in client:
{"partial" : ""}
{"partial" : ""}
{"partial" : ""}
{"partial" : ""}
{"partial" : ""}
{"partial" : ""}
{"partial" : "yes"}
Traceback (most recent call last):
  File "asr-test.py", line 38, in <module>
    test_stream()
  File "asr-test.py", line 36, in test_stream
    process_final_chunk(ws)
  File "asr-test.py", line 19, in process_final_chunk
    res = ws.recv()
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python3.6/site-packages/websocket/_socket.py", line 115, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

in server:
LOG ([5.5]:Model():model.cc:39) Sample rate is 16000
server --feature-type=mfcc --mfcc-config=model/mfcc.conf --min-active=200 --max-active=6000 --beam=13.0 --lattice-beam=6.0 --acoustic-scale=1.0 --frame-subsampling-factor=3 --endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10 --endpoint.rule2.min-trailing-silence=0.5 --endpoint.rule3.min-trailing-silence=1.0 --endpoint.rule4.min-trailing-silence=2.0 --ivector-silence-weighting.silence-weight=0.001 --ivector-silence-weighting.silence-phones=1:2:3:4:5:6:7:8:9:10 --ivector-extraction-config=model/ivector/ivector.conf
LOG (server[5.5]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 5 orphan nodes.
LOG (server[5.5]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 11 orphan components.
LOG (server[5.5]:Collapse():nnet-utils.cc:1463) Added 6 components, removed 11
LOG (server[5.5]:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0832829 seconds in looped compilation.
LOG (server[5.5]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (server[5.5]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
Segmentation fault

My modified code is here

[modified.zip](https://github.com/alphacep/kaldi-websocket-python/files/3614938/modified.zip)

How can I solve this problem?

Thank you!

**Comment by nshmyrev** [comment]
The cache object lm_compose_cache_ has to be decoder-specific, you can even create it for every rescoring instead of storing it in the Model object. You can also compose lattice and lmfst without cache, with simple fst::Compose instead of TableCompose.

Try it and let me know.

**Comment by attitudezoe** [comment]
I delete lm_compose_cache_ in model object, and modified 
 fst::TableCompose(tmp_lattice, *model_.lm_fst_, &composed_lat, lm_compose_cache_);
 in kaldi_recognizer.cc as follows:
  fst::Compose(tmp_lattice, *model_.lm_fst_, &composed_lat);

The above error still exists.

**Comment by nshmyrev** [comment]
Move lm_fst and mapper to decoder as well, only leave std_lm_fst in the model. Do not delete std_lm_fst.

**Comment by attitudezoe** [comment]
There is no error now,  thank you !

**Comment by nshmyrev** [comment]
Congratulations! Consider a pull request!

**Comment by sumeet559** [comment]
Can you share exactly what to do? I am facing the same problem but I am not able to find fst::TableCompose
