### ISSUE TITLE
concurrent issue

### ISSUE THREAD

**Issue by qo6xup6** [alphacep/kaldi-websocket-python#12]
Hi, I was running some pressure testing with your prototype ( with JMeter 5.1.1 and WebSocket plugin 1.2.2 ).

Didn't add other framework such as Gunicorn or Tornado, same as asyncio and Python3 websockets you used in this repo.

I'm running it on a machine with 32GB RAM and 12 CPUs, but the throughput is very low.

In most of the cases, I got time-out error, I noticed that CPU% usages went up so decoding is using multiple CPUs for sue, but the overall performance is still bad. Already compiled it with -thread as the fix in your last commit.

If I comment out decoding part, and simply send string message back to client, throughput went up to over 3000 directly. I was wondering which part went south for my testing. Thanks!

![Screenshot from 2019-09-25 09-52-54](https://user-images.githubusercontent.com/17018853/65562822-4f3e5500-df7a-11e9-837a-ac1f7a9c6ef5.png)

**Comment by nshmyrev** [comment]
Ok, please provided required files to reproduce this thing. Websocket_asr.jmx at least.

**Comment by qo6xup6** [comment]
Please check the attached JMX file, tyvm.

[Test Plan - WebSocket ASR.jmx.tar.gz](https://github.com/alphacep/kaldi-websocket-python/files/3650618/Test.Plan.-.WebSocket.ASR.jmx.tar.gz)

**Comment by nshmyrev** [comment]
Hi

I see the full load with jmeter, but still investigating

```
Creating summariser <summary>
Created the tree successfully using test.jmx
Starting the test @ Mon Sep 30 22:08:36 CEST 2019 (1569874116946)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +    133 in 00:00:23 =    5.7/s Avg:  1491 Min:     0 Max:  6006 Err:    20 (15.04%) Active: 10 Started: 10 Finished: 0
summary +    168 in 00:00:30 =    5.6/s Avg:  1791 Min:     0 Max:  6006 Err:    30 (17.86%) Active: 10 Started: 10 Finished: 0
summary =    301 in 00:00:53 =    5.7/s Avg:  1659 Min:     0 Max:  6006 Err:    50 (16.61%)
summary +    162 in 00:00:30 =    5.4/s Avg:  1804 Min:     0 Max:  6006 Err:    29 (17.90%) Active: 10 Started: 10 Finished: 0
summary =    463 in 00:01:23 =    5.6/s Avg:  1709 Min:     0 Max:  6006 Err:    79 (17.06%)
summary +    178 in 00:00:30 =    5.9/s Avg:  1722 Min:     0 Max:  6006 Err:    29 (16.29%) Active: 10 Started: 10 Finished: 0
summary =    641 in 00:01:53 =    5.7/s Avg:  1713 Min:     0 Max:  6006 Err:   108 (16.85%)
summary +     55 in 00:00:12 =    4.7/s Avg:  2232 Min:     0 Max:  6006 Err:    12 (21.82%) Active: 0 Started: 10 Finished: 10
summary =    696 in 00:02:05 =    5.6/s Avg:  1754 Min:     0 Max:  6006 Err:   120 (17.24%)
Tidying up ...    @ Mon Sep 30 22:10:41 CEST 2019 (1569874241964)
... end of run

```

**Comment by nshmyrev** [comment]
Ok, I figured that out the jmeter thing.

The default beams might be slow to process that many requests in parallel. You need to check the batch decoder logs for RT ratio first of all and tune beams accordingly (and model size/ architecture). If you want to process many requests, you need to lower beams and make smaller model. With smaller beams (max-active=4000, beam=10.0) I get this:

```
Creating summariser <summary>
Created the tree successfully using test.jmx
Starting the test @ Mon Sep 30 22:44:14 CEST 2019 (1569876254952)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +    487 in 00:00:15 =   33.0/s Avg:   260 Min:     0 Max:  1832 Err:     0 (0.00%) Active: 10 Started: 10 Finished: 0
summary +   1108 in 00:00:30 =   37.0/s Avg:   269 Min:     0 Max:  1734 Err:     0 (0.00%) Active: 10 Started: 10 Finished: 0
summary =   1595 in 00:00:45 =   35.7/s Avg:   267 Min:     0 Max:  1832 Err:     0 (0.00%)
summary +   1108 in 00:00:30 =   36.9/s Avg:   270 Min:     0 Max:  1757 Err:     0 (0.00%) Active: 10 Started: 10 Finished: 0
summary =   2703 in 00:01:15 =   36.2/s Avg:   268 Min:     0 Max:  1832 Err:     0 (0.00%)
summary +   1122 in 00:00:30 =   37.4/s Avg:   268 Min:     0 Max:  1788 Err:     0 (0.00%) Active: 10 Started: 10 Finished: 0
summary =   3825 in 00:01:45 =   36.5/s Avg:   268 Min:     0 Max:  1832 Err:     0 (0.00%)
summary +    617 in 00:00:17 =   35.6/s Avg:   284 Min:     0 Max:  1741 Err:     0 (0.00%) Active: 0 Started: 10 Finished: 10
summary =   4442 in 00:02:02 =   36.4/s Avg:   270 Min:     0 Max:  1832 Err:     0 (0.00%)
Tidying up ...    @ Mon Sep 30 22:46:17 CEST 2019 (1569876377348)
... end of run

```

You can also tune jmeter to fix RPS ratio with something like this probably: https://jmeter-plugins.org/wiki/ThroughputShapingTimer/

**Comment by nshmyrev** [comment]
Let me know if you need further help on this.

**Comment by qo6xup6** [comment]
> Let me know if you need further help on this.

Many thanks :)
