### ISSUE TITLE
Active Grammar

### ISSUE THREAD

**Issue by yondu22** [alphacep/kaldi-websocket-python#15]
Do you have any suggestions on how we can integrate active grammar into the websocket api
https://github.com/daanzu/kaldi-active-grammar
This would be similiar to google's phrase hint api, allowing us to weight certain phrases and words in decoding

**Comment by nshmyrev** [comment]
Hi

It is all possible, you can use kaldi-active grammar, or C++ API like https://kaldi-asr.org/doc/grammar.html directly. You can also check https://github.com/kaldi-asr/kaldi/pull/3616 pull request which is not yet complete, but kinda helps to quickly weight words in the grammar. There are no immediate plans to implement it in this server unfortunately.
