### ISSUE TITLE
Bad recognition results with custom/German audio model

### ISSUE THREAD

**Issue by fels97** [alphacep/kaldi-websocket-python#19]
Hi,

First of all: Thank you so much for your effort on my last issue  ( #17 ).

I downloaded the new image and it worked just fine, nothing crashed. I think the problem when I tried to run the model was the fact that there are two files "mfcc.conf" and "mfcc_hires.conf" contained in this German audio model and then I assumed I'd need the first one when I actually needed to add "mfcc_hires.conf" to the container's model renamed as "mfcc.conf".

Now I've got a new problem: The delivered transcription output of the server is pretty horrible.
Sometimes the recognised words are mostly wrong or the text output is just empty (which I think was due to badly converted audio files).
I've tried a lot of different stuff trying to fix this issue, like changing the parameters of model.cc to the values given in the audio model's .yaml file, adding phones.txt and referencing it in model.cc and model.h (I let the image rebuild and compile itself with the changed files so they'd apply), changing the sample_frequency (tried with 8kHz and 16kHz on both the model settings aswell as the wav files I used to test the server), but nothing seems to help in any way.
Do you happen to have an idea on what I can change so the server outputs transcriptions which are as good as I'd expect from using that certain audio model?

**Comment by fels97** [comment]
I fixed it:
Seems like the German audio model I was using only works properly with a sample rate of 16kHz which I oversaw since the 16kHz audio files I used were somehow corrupted (probably due to a bad conversion tool). I tried it again now with a different audio converter and it perfectly translates everything now.

**Comment by nshmyrev** [comment]
Ok, congratulations!
