### ISSUE TITLE
Make in Lookahead

### ISSUE THREAD

**Issue by qo6xup6** [alphacep/kaldi-websocket-python#22]
When I was trying to make in lookahread branch.
Got the following error:

kaldi_recognizer.h:35:14: error: ‘LookaheadFst’ in namespace ‘fst’ does not name a template type

I'm using the latest master branch of Kaldi and have upgraded fst from 1.6.7 to even 1.7.5(latest version) but seems Lookahead doesn't exist in fst namespace.
Am I missing anything or ./configure in openfst incorrectly?

**Comment by nshmyrev** [comment]
You need to compile kaldi from https://github.com/alphacep/kaldi lookahead branch too, did you compile it?

**Comment by qo6xup6** [comment]
I was using original kaldi-asr repo and recompiling fst 1.6.7 with --enable-lookahead-fsts
Not sure if it will work or not.

**Comment by nshmyrev** [comment]
No, it has some modifications, see https://github.com/kaldi-asr/kaldi/pull/3616 for details

**Comment by qo6xup6** [comment]
So it's not merged into native kaldi, thanks for this notification.
Will try it :) much appreciated.

**Comment by nshmyrev** [comment]
Ok, let me know how it goes

**Comment by qo6xup6** [comment]
Get this error while compiling FST:
`/usr/bin/ld: ~/kaldi/tools/openfst/lib/libfst.a(flags.o): relocation R_X86_64_32 against '.bss' can not be used when making a shared object; recompile with -fPIC`
Solved by adding `-fPIC` into CXXFLAGS and recompile it.

When configuring kaldi/src, use --MATHLIB=ATLAS instead of default MKL.
Otherwise will report `undefined symbol: vsPowx`

Now compilation is done, need to make a new model to test.
Missing `HCLr.fst` and `Gr.fst`

Thanks for your help :)

**Comment by nshmyrev** [comment]
> Get this error while compiling FST:
/usr/bin/ld: ~/kaldi/tools/openfst/lib/libfst.a(flags.o): relocation R_X86_64_32 against '.bss' can not be used when making a shared object; recompile with -fPIC
Solved by adding -fPIC into CXXFLAGS and recompile it

This is why it has `--with-pic` in fst configure in tools/Makefile.
