### ISSUE TITLE
Lookahead Model

### ISSUE THREAD

**Issue by qo6xup6** [alphacep/kaldi-websocket-python#23]
I have used this command `utils/mkgraph_lookahead.sh --self-loop-scale 1.0 --remove-oov --compose-graph` from `run_lookahead.sh`.

Provide model from Zamia, but when I try running `asr_server.py`, it reports `ERROR: Fst::Read: Unknown FST type const (arc type = standard): model/Gr.fst` 

But same Zamia model is working in original WebSocket ASR server.
Wondering if I did any step incorrectly.

**Comment by nshmyrev** [comment]
I'll fix it. Meanwhile, it is only supposed to work with mkgraph_lookahead_arpa, not mkgraph_lookahead.

**Comment by qo6xup6** [comment]
After installing opengram and srilm, run `mkgraph_lookahead_arpa.sh` reporting similar error:

`ERROR: GenericRegister::GetEntry: olabel_lookahead-fst.so: cannot open shared object file: No such file or directory`

`FATAL: Fst::Convert: Unknown FST type olabel_lookahead (arc type standard)`

**Comment by nshmyrev** [comment]
You need to set LD_LIBRARY_PATH to openfst/lib/fst

**Comment by qo6xup6** [comment]
Oh yeah, I've skipped it from `run_lookahead.sh`, thanks!

**Comment by nshmyrev** [comment]
Fixed in 44e98773c9f505a6e8e69db8717f46add584b788
