### ISSUE TITLE
how to server zamia pre trained asr model

### ISSUE THREAD

**Issue by cogmeta** [alphacep/kaldi-websocket-python#25]
Can we use this to serve zamia pre trained models from here https://github.com/gooofy/zamia-speech? We are trying to export zamia speech model to the format expected by kaldi-websocket-python but for some reason asr_server.py keeps crashing

**Comment by cogmeta** [comment]
LOG (server[5.5.0~1-1f35]:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0754251 seconds in looped compilation.
ERROR (server[5.5.0~1-1f35]:OnlineTransform():online-feature.cc:533) Dimension mismatch: source features have dimension 91 and L
DA #cols is 280

**Comment by nshmyrev** [comment]
You probably took mfcc.conf from the model, you should take mfcc_hires.conf instead. Otherwise it should work fine.

**Comment by cogmeta** [comment]
Works! Thank you.

**Comment by cogmeta** [comment]
Brilliant! We ended up moving the decoder code to grpc server and It is working amazingly well. 10 concurrent requests on a 4 core cpu  works well. Thank you.
