### ISSUE TITLE
Makefile:41: recipe for target '_kaldi_recognizer.so' failed

### ISSUE THREAD

**Issue by binglel** [alphacep/kaldi-websocket-python#29]
When I compile, I get the following error.
yielded this error:
`t$ make
g++ -std=c++11 -g -Wall -DPIC -fPIC -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/binglel/kaldi/tools/ATLAS/include -I/home/binglel/kaldi/tools/openfst/include -I/home/binglel/kaldi/src `pkg-config --cflags python3` -shared -o _kaldi_recognizer.so kaldi_recognizer.cc model.cc kaldi_recognizer_wrap.cc -rdynamic -Wl,-rpath=/home/binglel/kaldi/tools/openfst/lib /home/binglel/kaldi/src/online2/kaldi-online2.a /home/binglel/kaldi/src/decoder/kaldi-decoder.a /home/binglel/kaldi/src/ivector/kaldi-ivector.a /home/binglel/kaldi/src/gmm/kaldi-gmm.a /home/binglel/kaldi/src/nnet3/kaldi-nnet3.a /home/binglel/kaldi/src/tree/kaldi-tree.a /home/binglel/kaldi/src/feat/kaldi-feat.a /home/binglel/kaldi/src/lat/kaldi-lat.a /home/binglel/kaldi/src/hmm/kaldi-hmm.a /home/binglel/kaldi/src/transform/kaldi-transform.a /home/binglel/kaldi/src/cudamatrix/kaldi-cudamatrix.a /home/binglel/kaldi/src/matrix/kaldi-matrix.a /home/binglel/kaldi/src/fstext/kaldi-fstext.a /home/binglel/kaldi/src/util/kaldi-util.a /home/binglel/kaldi/src/base/kaldi-base.a -L /home/binglel/kaldi/tools/openfst/lib -lfst /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 `pkg-config --libs python3` -lm -lpthread
g++: error: /home/binglel/kaldi/src/online2/kaldi-online2.a: No such file or directory
g++: error: /home/binglel/kaldi/src/decoder/kaldi-decoder.a: No such file or directory
g++: error: /home/binglel/kaldi/src/ivector/kaldi-ivector.a: No such file or directory
g++: error: /home/binglel/kaldi/src/gmm/kaldi-gmm.a: No such file or directory
g++: error: /home/binglel/kaldi/src/nnet3/kaldi-nnet3.a: No such file or directory
g++: error: /home/binglel/kaldi/src/tree/kaldi-tree.a: No such file or directory
g++: error: /home/binglel/kaldi/src/feat/kaldi-feat.a: No such file or directory
g++: error: /home/binglel/kaldi/src/lat/kaldi-lat.a: No such file or directory
g++: error: /home/binglel/kaldi/src/hmm/kaldi-hmm.a: No such file or directory
g++: error: /home/binglel/kaldi/src/transform/kaldi-transform.a: No such file or directory
g++: error: /home/binglel/kaldi/src/cudamatrix/kaldi-cudamatrix.a: No such file or directory
g++: error: /home/binglel/kaldi/src/matrix/kaldi-matrix.a: No such file or directory
g++: error: /home/binglel/kaldi/src/fstext/kaldi-fstext.a: No such file or directory
g++: error: /home/binglel/kaldi/src/util/kaldi-util.a: No such file or directory
g++: error: /home/binglel/kaldi/src/base/kaldi-base.a: No such file or directory
g++: error: /usr/lib/libatlas.so.3: No such file or directory
g++: error: /usr/lib/libf77blas.so.3: No such file or directory
g++: error: /usr/lib/libcblas.so.3: No such file or directory
g++: error: /usr/lib/liblapack_atlas.so.3: No such file or directory
Makefile:41: recipe for target '_kaldi_recognizer.so' failed
make: *** [_kaldi_recognizer.so] Error 1`

Ask for your help. thanks!

**Comment by YunzhaoLu** [comment]
compile kaldi first.

**Comment by binglel** [comment]
I get, my kaldi path is bad. thanks!

**Comment by nshmyrev** [comment]
Ok, please let us know how it goes. Overall, compilation flags must match Kaldi flags. Or use docker , it is easier.
