### ISSUE TITLE
Testing the server

### ISSUE THREAD

**Issue by ahmetaa** [alphacep/kaldi-websocket-python#3]
Server code is up and running.  However I am not sure if it is expecting a wav file data or raw bytes. Sampling rate was hardcoded to 8000 so I changed to 16000. 
Can you give a very basic client code example or give a hint on how to test the server with a wav file?

**Comment by nshmyrev** [comment]
https://github.com/alphacep/api-samples

**Comment by ahmetaa** [comment]
Thanks again. It works.
