### ISSUE TITLE
example and describe to use

### ISSUE THREAD

**Issue by lalimili6** [alphacep/kaldi-websocket-python#5]
Hi 
Is it possible for an example to use this code? 
This code sends a wave to port and gives text?
can use lm re-scoring and give 10-best transcript? 
what are differences between this code and TCP decoding code in Kaldi?
best regards

**Comment by nshmyrev** [comment]
> Is it possible for an example to use this code?

Yes, you run the server like this:

`./asr_server.py`

then you run any amount of clients in parallel:

`./test.py test.wav`

> This code sends a wave to port and gives text?

Not just text but json with words, timestamps and decoding variants.

> can use lm re-scoring and give 10-best transcript?

Yes

> what are differences between this code and TCP decoding code in Kaldi?

It can be load-balanced properly 

Ot properly implements parallel decoding with model sharing and async IO.

**Comment by lalimili6** [comment]
Is it possible that send raw wave from microphone to the port? Do you have any example?

best regards

**Comment by nshmyrev** [comment]
Some examples here https://github.com/alphacep/api-samples
