### ISSUE TITLE
question on add big lm rescore function

### ISSUE THREAD

**Issue by attitudezoe** [alphacep/kaldi-websocket-python#8]
Hi,
I found there was no big lm re-scoring in the code.
I tried to add it:
I add script in model.cc: 
    old_lm_fst_ = "model/G.fst";
    big_lm_arpa_ = "model/G.carpa";
    std_lm_fst_ = fst::ReadFstKaldi(old_lm_fst_);
    kaldi::ReadKaldiObject(big_lm_arpa_, &const_arpa_);
and in model.h:
   std::string old_lm_fst_;
   std::string big_lm_arpa_;
   fst::VectorFst<fst::StdArc> *std_lm_fst_;
   kaldi::ConstArpaLm const_arpa_;

There was no problem in create _kaldi_recognizer.so,
but when run asr_server.py, I got  the following error:

ImportError: /data/kaldi-websocket-python-master_resore/_kaldi_recognizer.so: undefined symbol: _ZN5kaldi11ConstArpaLm4ReadERSib

How can I solve this problem?

Thank you.

**Comment by nshmyrev** [comment]
In makefile add library

`$(KALDI_ROOT)/src/lm/kaldi-lm.a \`
