### ISSUE TITLE
Multiple Request Handling

### ISSUE THREAD

**Issue by cemildemir19** [alphacep/kaldi-websocket-python#9]
when i run kaldi-web-socket python implementation with multiple concurrent requests, it uses single  cpu to decode all concurrent calls. it slows down the system response. how can i solve this problem?

**Comment by madkote** [comment]
)) that was the first, I noticed in the implementation by looking in the code.

**Comment by madkote** [comment]
decoding is blocking operation, so you need to *unblock* it or wait for truly *async* implementation.

**Comment by nshmyrev** [comment]
Fixed in f8f4a33, thank you for the report!

**Comment by yondu22** [comment]
For concurrent, and multithreading do we need to write a new server script, or would the asr-server.py work? I tried to just run python asr-server.py using a 8 core cpu, i7 and I can only do 1 concurrent decoding at the same time using jmeter for testing.

**Comment by cemildemir19** [comment]
i tested with asr_server script on the repo, it can successfully responses to 4 concurrent requests.

**Comment by yondu22** [comment]
@cemildemir19 what did you do, did you change the thread number? or just run as is? what did you use for the client to send the responses?

**Comment by cemildemir19** [comment]
i run as it is. it increased the cpu usage automatically.

**Comment by yondu22** [comment]
@cemildemir19 thank you, is 4 the maximum you can get? What is your cpu specs. It is strange why I can only get 1 concurrent, with gstreamer, i could load 50-100 workers and perform that many concurrent. I was led here because it was mentioned that his is better for concurrency than gstreamer

**Comment by cemildemir19** [comment]
i also tried with 6 for you. it has no problem. there are 6 cores in my laptop. cpu model is Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz.

**Comment by nshmyrev** [comment]
It works fine, just make sure you updated the code with this fix.

**Comment by yondu22** [comment]
@cemildemir19 @nshmyrev do you have a guide to .jmx file so I can try to repeat the concurrent testing, I am not able to achieve concurrency with JMeter

**Comment by cemildemir19** [comment]
sorry i do not use JMeter. Therefore, i do not have a guide.

**Comment by nshmyrev** [comment]
@yondu22 you can just run many clients from command line in parallel:

`parallel -j 20 ./test.py test.wav ::: {1..100}`

**Comment by nshmyrev** [comment]
Continue in #12

**Comment by bofh7** [comment]
@nshmyrev Thanks for this great work.

However I'm wondering why you used `concurrent.futures.ThreadPoolExecutor()` to process the chunk instead of `concurrent.futures.ProcessPoolExecutor()`, which is not limited by GIL ?

**Comment by madkote** [comment]
> 
> I'm wondering in [f8f4a33](https://github.com/alphacep/vosk-server/commit/f8f4a331a4369752c12686a1d90f52d39bd6a48f) why you used `concurrent.futures.ThreadPoolExecutor()` to process the chunk instead of `concurrent.futures.ProcessPoolExecutor()`, which is not limited by GIL ?

@bofh7 have you tried? Once I run into memory issues with this approach.

**Comment by bofh7** [comment]
@madkote me too, I got some errors here.

```
TypeError: cannot pickle 'SwigPyObject' object
```

However when I ran 2 or 3 concurrent clients, it took almost the same time with 1 client. So I'm wondering if the calculations for decoding chunks were somehow parallelized ?

**Comment by madkote** [comment]
@bofh7 Exactly. I run into same issue, and never had time to look deeply into this. You might want to check the cpp code of the decoder. But I do not think there is anything parallelized.
